### PR TITLE
Handle empty spans in `invert_spans`

### LINKED ISSUE #47: `invert_spans` doesn't handle the empty `spans` case
```julia
julia> invert_spans(TimeSpan[], TimeSpan(0, 10))
ERROR: BoundsError: attempt to access 0-element Vector{TimeSpan} at index [1]
Stacktrace:
 [1] getindex
   @ ./array.jl:924 [inlined]
 [2] first
   @ ./abstractarray.jl:404 [inlined]
 [3] invert_spans(spans::Vector{TimeSpan}, parent_span::TimeSpan)
   @ TimeSpans ~/.julia/packages/TimeSpans/EIPIX/src/TimeSpans.jl:370
 [4] top-level scope
   @ REPL[98]:1
```
This should just return the parent, I believe, as a singleton vector.

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #47. Once this is merged I'll backport the commit to 0.2.

### CODE REVIEW

**Review by ericphanson — APPROVED** [review]

File: src/TimeSpans.jl [hunk 1]
```diff
@@ -371,6 +371,7 @@ Return a vector of `TimeSpan`s representing the gaps between the spans in the
 iterable `spans` that are contained within `parent_span`.
 """
 function invert_spans(spans, parent_span)
+    isempty(spans) && return TimeSpan[parent_span]
```
Comment (ericphanson) [inline src/TimeSpans.jl:374]: Maybe this is better? So we hit the same `start` and `stop` (via the constructor) as in the other branch, rather than a `convert`:
```suggestion
    isempty(spans) && return[TimeSpan(parent_span)]
```

Comment (ararslan) [reply src/TimeSpans.jl]: I actually had that initially and changed it but I have no idea why
